import {response} from '../lib/arakawa.mjs';
const WARNING='https://www.jma.go.jp/bosai/warning/data/warning/130000.json';
const FORECAST='https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json';
const RADAR='https://www.jma.go.jp/bosai/jmatile/data/nowc/targetTimes_N1.json';
async function getJson(url){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'ArakawaFloodDashboard/0.8'},signal:AbortSignal.timeout(10000),cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
function warningPart(d){const area=(d.areaTypes||[]).flatMap(t=>t.areas||[]).find(x=>x.code==='1311800');if(!area||!Array.isArray(area.warnings))throw Error('荒川区の警報一覧を確認できません');return{state:'ok',reportDatetime:d.reportDatetime||null,warnings:area.warnings}}
function forecastPart(a){const d=a?.[0],w=d?.timeSeries?.[0],area=w?.areas?.find(x=>x.area?.code==='130010'),ps=d?.timeSeries?.[1],p=ps?.areas?.find(x=>x.area?.code==='130010');if(!area)throw Error('東京地方の予報を確認できません');return{state:'ok',reportDatetime:d.reportDatetime||null,weather:area.weathers?.[0]||'',pops:(p?.pops||[]).map((pop,i)=>({time:ps.timeDefines?.[i]||null,pop})).filter(x=>x.time)}}
function parseJmaTime(s){if(!/^\d{14}$/.test(String(s)))return NaN;return Date.UTC(+s.slice(0,4),+s.slice(4,6)-1,+s.slice(6,8),+s.slice(8,10),+s.slice(10,12),+s.slice(12,14))}
function radarPart(a){const now=Date.now(),items=(Array.isArray(a)?a:[]).filter(x=>x?.basetime&&x?.validtime&&(x.elements||[]).includes('hrpns')).sort((x,y)=>String(y.validtime).localeCompare(String(x.validtime))),latest=items.find(x=>parseJmaTime(x.validtime)<=now+10*60000)||items[0];if(!latest)throw Error('雨雲タイル時刻を確認できません');return{state:'ok',basetime:latest.basetime,validtime:latest.validtime,timestamp:new Date(parseJmaTime(latest.validtime)).toISOString()}}
const safe=(r,fn)=>{if(r.status!=='fulfilled')return{state:'error',error:String(r.reason?.message||r.reason)};try{return fn(r.value)}catch(e){return{state:'error',error:String(e.message||e)}}};
export default async function(req,res){if(req.method!=='GET')return response(res,405,{error:'Method not allowed'});const [w,f,r]=await Promise.allSettled([getJson(WARNING),getJson(FORECAST),getJson(RADAR)]);return response(res,200,{warning:safe(w,warningPart),forecast:safe(f,forecastPart),radar:safe(r,radarPart),retrievedAt:new Date().toISOString()})}
